http:
  routers:
    # Define a connection between requests and services
    to-foo:
      rule: "Host(`foo.com`)"
      # If the rule matches, forward to the whoami service (declared below)
      service: whoami

  services:
    # Define how to reach an existing service on our infrastructure
    whoami:
      loadBalancer:
        servers:
          - url: http://IP_ADDRESS:30000
